### ISSUE TITLE
GNious UDP beta (probably earlier, though) listener not finding all bulbs

### ISSUE THREAD

**Issue by jheld** [sharph/lifx-python#9]
@GNious, @sharph here is the tcpdump from my raspberry pi based on me opening my android app (i stopped running it after about 10 seconds....):

pi@raspberrypi ~/lifx_django/lifx_management $ sudo tcpdump -nvx 'udp port 56700'
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
20:09:36.143193 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 64)
    192.168.0.109.56700 > 192.168.0.255.56700: UDP, length 36
    0x0000:  4500 0040 0000 4000 4011 b7f0 c0a8 006d
    0x0010:  c0a8 00ff dd7c dd7c 002c 9bab 2400 0034
    0x0020:  0000 0000 0000 0000 0000 0000 0000 0000
    0x0030:  0000 0000 0000 0000 0000 0000 0200 0000
20:09:37.092118 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 64)
    192.168.0.109.56700 > 192.168.0.255.56700: UDP, length 36
    0x0000:  4500 0040 0000 4000 4011 b7f0 c0a8 006d
    0x0010:  c0a8 00ff dd7c dd7c 002c 9bab 2400 0034
    0x0020:  0000 0000 0000 0000 0000 0000 0000 0000
    0x0030:  0000 0000 0000 0000 0000 0000 0200 0000
20:09:37.142879 IP (tos 0x0, ttl 255, id 1582, offset 0, flags [DF], proto UDP (17), length 69)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 41
    0x0000:  4500 0045 062e 4000 ff11 f2bf c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0031 5e59 2900 0054
    0x0020:  0000 0000 d073 d500 a6e2 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 0300 0000
    0x0040:  0200 0000 00
20:09:37.142883 IP (tos 0x0, ttl 255, id 1445, offset 0, flags [DF], proto UDP (17), length 69)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 41
    0x0000:  4500 0045 05a5 4000 ff11 f34c c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0031 b8dd 2900 0054
    0x0020:  0000 0000 d073 d501 4c61 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 0300 0000
    0x0040:  0200 0000 00
20:09:37.144240 IP (tos 0x0, ttl 255, id 1583, offset 0, flags [DF], proto UDP (17), length 69)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 41
    0x0000:  4500 0045 062f 4000 ff11 f2be c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0031 81dc 2900 0054
    0x0020:  0000 0000 d073 d500 a6e2 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 0300 0000
    0x0040:  017c dd00 00
20:09:37.144614 IP (tos 0x0, ttl 255, id 1446, offset 0, flags [DF], proto UDP (17), length 69)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 41
    0x0000:  4500 0045 05a6 4000 ff11 f34b c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0031 dc60 2900 0054
    0x0020:  0000 0000 d073 d501 4c61 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 0300 0000
    0x0040:  017c dd00 00
20:09:37.979506 IP (tos 0x0, ttl 255, id 1584, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 0630 4000 ff11 f28e c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0060 425f 5800 0054
    0x0020:  0000 0000 d073 d500 a6e2 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  aaaa 0000 d12a a00f 0000 0000 6c61 6d70
    0x0050:  2074 6f70 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0100 0000
    0x0070:  0000 0000
20:09:37.981079 IP (tos 0x0, ttl 255, id 1447, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 05a7 4000 ff11 f31b c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0060 2e1a 5800 0054
    0x0020:  0000 0000 d073 d501 4c61 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  4404 0000 e404 480d 0000 0000 6d69 7272
    0x0050:  6f72 3200 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0400 0000
    0x0070:  0000 0000
20:09:37.998965 IP (tos 0x0, ttl 255, id 1448, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 05a8 4000 ff11 f31a c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0060 fe69 5800 0054
    0x0020:  0000 0000 d073 d500 8fff 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  a4ef 0000 a838 9411 0000 ffff 6b69 7463
    0x0050:  6865 6e20 7374 6f76 6500 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0200 0000
    0x0070:  0000 0000
20:09:38.013866 IP (tos 0x0, ttl 255, id 1449, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 05a9 4000 ff11 f319 c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0060 5a1b 5800 0054
    0x0020:  0000 0000 d073 d500 c465 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  87e8 0000 7036 9411 0000 0000 6861 6c6c
    0x0050:  7761 7900 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0000 0000
    0x0070:  0000 0000
20:09:38.017792 IP (tos 0x0, ttl 255, id 1585, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 0631 4000 ff11 f28d c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0060 fe65 5800 0054
    0x0020:  0000 0000 d073 d500 8fff 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  a4ef 0000 a838 9411 0000 ffff 6b69 7463
    0x0050:  6865 6e20 7374 6f76 6500 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0200 0000
    0x0070:  0000 0000
20:09:38.025394 IP (tos 0x0, ttl 255, id 1450, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 05aa 4000 ff11 f318 c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0060 2245 5800 0054
    0x0020:  0000 0000 d073 d500 91fd 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  fcff 0000 7d4e a00f 0000 0000 6365 696c
    0x0050:  696e 6700 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0400 0000
    0x0070:  0000 0000
20:09:38.035017 IP (tos 0x0, ttl 255, id 1451, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 05ab 4000 ff11 f317 c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0060 7d4a 5800 0054
    0x0020:  0000 0000 d073 d500 8f3a 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  c6b1 0000 714f 8813 0000 0000 6265 6472
    0x0050:  6f6f 6d00 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0000 0000
    0x0070:  0000 0000
20:09:38.047653 IP (tos 0x0, ttl 255, id 1586, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 0632 4000 ff11 f28c c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0060 9017 5800 0054
    0x0020:  0000 0000 d073 d500 b3d8 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  4efa 0000 5952 9411 0000 0000 6b69 7463
    0x0050:  6865 6e20 6672 6964 6765 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0200 0000
    0x0070:  0000 0000
20:09:38.057118 IP (tos 0x0, ttl 255, id 1452, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 05ac 4000 ff11 f316 c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0060 65e3 5800 0054
    0x0020:  0000 0000 d073 d500 9011 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  c096 0000 d92b 9411 0000 ffff 6c61 6d70
    0x0050:  2062 6f74 746f 6d00 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0100 0000
    0x0070:  0000 0000
20:09:38.067714 IP (tos 0x0, ttl 255, id 1587, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 0633 4000 ff11 f28b c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0060 5a17 5800 0054
    0x0020:  0000 0000 d073 d500 c465 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  87e8 0000 7036 9411 0000 0000 6861 6c6c
    0x0050:  7761 7900 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0000 0000
    0x0070:  0000 0000
20:09:38.081562 IP (tos 0x0, ttl 255, id 1453, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 05ad 4000 ff11 f315 c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0060 2bcf 5800 0054
    0x0020:  0000 0000 d073 d500 a7ff 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  a4ef 0000 c8e9 9411 0000 0000 6b69 7463
    0x0050:  6865 6e20 7369 6e6b 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0200 0000
    0x0070:  0000 0000
20:09:38.100959 IP (tos 0x0, ttl 255, id 1588, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 0634 4000 ff11 f28a c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0060 65df 5800 0054
    0x0020:  0000 0000 d073 d500 9011 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  c096 0000 d92b 9411 0000 ffff 6c61 6d70
    0x0050:  2062 6f74 746f 6d00 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0100 0000
    0x0070:  0000 0000
20:09:38.113008 IP (tos 0x0, ttl 255, id 1454, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 05ae 4000 ff11 f314 c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0060 901b 5800 0054
    0x0020:  0000 0000 d073 d500 b3d8 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  4efa 0000 5952 9411 0000 0000 6b69 7463
    0x0050:  6865 6e20 6672 6964 6765 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0200 0000
    0x0070:  0000 0000
20:09:38.136642 IP (tos 0x0, ttl 255, id 1589, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 0635 4000 ff11 f289 c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0060 2bcb 5800 0054
    0x0020:  0000 0000 d073 d500 a7ff 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  a4ef 0000 c8e9 9411 0000 0000 6b69 7463
    0x0050:  6865 6e20 7369 6e6b 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0200 0000
    0x0070:  0000 0000
20:09:38.145130 IP (tos 0x0, ttl 255, id 1455, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 05af 4000 ff11 f313 c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0060 cde5 5800 0054
    0x0020:  0000 0000 d073 d500 ad96 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  4404 0000 e404 480d 0000 0000 6d69 7272
    0x0050:  6f72 3100 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0400 0000
    0x0070:  0000 0000
20:09:38.147486 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 64)
    192.168.0.109.56700 > 192.168.0.255.56700: UDP, length 36
    0x0000:  4500 0040 0000 4000 4011 b7f0 c0a8 006d
    0x0010:  c0a8 00ff dd7c dd7c 002c 9bab 2400 0034
    0x0020:  0000 0000 0000 0000 0000 0000 0000 0000
    0x0030:  0000 0000 0000 0000 0000 0000 0200 0000
20:09:38.172734 IP (tos 0x0, ttl 255, id 1590, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 0636 4000 ff11 f288 c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0060 7d46 5800 0054
    0x0020:  0000 0000 d073 d500 8f3a 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  c6b1 0000 714f 8813 0000 0000 6265 6472
    0x0050:  6f6f 6d00 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0000 0000
    0x0070:  0000 0000
20:09:39.530745 IP (tos 0x0, ttl 255, id 1591, offset 0, flags [DF], proto UDP (17), length 104)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 76
    0x0000:  4500 0068 0637 4000 ff11 f293 c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0054 d1f6 4c00 0054
    0x0020:  0000 0000 d073 d500 a6e2 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 1f00 0000
    0x0040:  0100 0000 0000 0000 6c69 7669 6e67 2072
    0x0050:  6f6f 6d00 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000
20:09:39.532784 IP (tos 0x0, ttl 255, id 1592, offset 0, flags [DF], proto UDP (17), length 104)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 76
    0x0000:  4500 0068 0638 4000 ff11 f292 c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0054 68e0 4c00 0054
    0x0020:  0000 0000 d073 d500 a6e2 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 1f00 0000
    0x0040:  0200 0000 0000 0000 6b69 7463 6865 6e00
    0x0050:  0000 0000 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000
20:09:39.535487 IP (tos 0x0, ttl 255, id 1593, offset 0, flags [DF], proto UDP (17), length 104)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 76
    0x0000:  4500 0068 0639 4000 ff11 f291 c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0054 646c 4c00 0054
    0x0020:  0000 0000 d073 d500 a6e2 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 1f00 0000
    0x0040:  0400 0000 0000 0000 6261 7468 726f 6f6d
    0x0050:  0000 0000 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000
20:09:39.541484 IP (tos 0x0, ttl 255, id 1456, offset 0, flags [DF], proto UDP (17), length 104)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 76
    0x0000:  4500 0068 05b0 4000 ff11 f31e c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0054 2c7b 4c00 0054
    0x0020:  0000 0000 d073 d501 4c61 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 1f00 0000
    0x0040:  0100 0000 0000 0000 6c69 7669 6e67 2072
    0x0050:  6f6f 6d00 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000
20:09:39.542781 IP (tos 0x0, ttl 255, id 1457, offset 0, flags [DF], proto UDP (17), length 104)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 76
    0x0000:  4500 0068 05b1 4000 ff11 f31d c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0054 c364 4c00 0054
    0x0020:  0000 0000 d073 d501 4c61 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 1f00 0000
    0x0040:  0200 0000 0000 0000 6b69 7463 6865 6e00
    0x0050:  0000 0000 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000
20:09:39.544920 IP (tos 0x0, ttl 255, id 1458, offset 0, flags [DF], proto UDP (17), length 104)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 76
    0x0000:  4500 0068 05b2 4000 ff11 f31c c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0054 bef0 4c00 0054
    0x0020:  0000 0000 d073 d501 4c61 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 1f00 0000
    0x0040:  0400 0000 0000 0000 6261 7468 726f 6f6d
    0x0050:  0000 0000 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000
20:09:41.542672 IP (tos 0x0, ttl 255, id 1594, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 063a 4000 ff11 f284 c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0060 425f 5800 0054
    0x0020:  0000 0000 d073 d500 a6e2 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  aaaa 0000 d12a a00f 0000 0000 6c61 6d70
    0x0050:  2074 6f70 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0100 0000
    0x0070:  0000 0000
20:09:41.543037 IP (tos 0x0, ttl 255, id 1459, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 05b3 4000 ff11 f30f c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0060 2e1a 5800 0054
    0x0020:  0000 0000 d073 d501 4c61 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  4404 0000 e404 480d 0000 0000 6d69 7272
    0x0050:  6f72 3200 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0400 0000
    0x0070:  0000 0000
20:09:41.563051 IP (tos 0x0, ttl 255, id 1595, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 063b 4000 ff11 f283 c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0060 fe65 5800 0054
    0x0020:  0000 0000 d073 d500 8fff 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  a4ef 0000 a838 9411 0000 ffff 6b69 7463
    0x0050:  6865 6e20 7374 6f76 6500 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0200 0000
    0x0070:  0000 0000
20:09:41.574588 IP (tos 0x0, ttl 255, id 1596, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 063c 4000 ff11 f282 c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0060 65df 5800 0054
    0x0020:  0000 0000 d073 d500 9011 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  c096 0000 d92b 9411 0000 ffff 6c61 6d70
    0x0050:  2062 6f74 746f 6d00 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0100 0000
    0x0070:  0000 0000
20:09:41.594581 IP (tos 0x0, ttl 255, id 1597, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 063d 4000 ff11 f281 c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0060 2241 5800 0054
    0x0020:  0000 0000 d073 d500 91fd 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  fcff 0000 7d4e a00f 0000 0000 6365 696c
    0x0050:  696e 6700 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0400 0000
    0x0070:  0000 0000
20:09:41.622668 IP (tos 0x0, ttl 255, id 1598, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 063e 4000 ff11 f280 c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0060 5a17 5800 0054
    0x0020:  0000 0000 d073 d500 c465 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  87e8 0000 7036 9411 0000 0000 6861 6c6c
    0x0050:  7761 7900 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0000 0000
    0x0070:  0000 0000
20:09:41.630776 IP (tos 0x0, ttl 255, id 1460, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 05b4 4000 ff11 f30e c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0060 cde5 5800 0054
    0x0020:  0000 0000 d073 d500 ad96 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  4404 0000 e404 480d 0000 0000 6d69 7272
    0x0050:  6f72 3100 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0400 0000
    0x0070:  0000 0000
20:09:41.652761 IP (tos 0x0, ttl 255, id 1461, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 05b5 4000 ff11 f30d c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0060 5a1b 5800 0054
    0x0020:  0000 0000 d073 d500 c465 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  87e8 0000 7036 9411 0000 0000 6861 6c6c
    0x0050:  7761 7900 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0000 0000
    0x0070:  0000 0000
20:09:41.666122 IP (tos 0x0, ttl 255, id 1462, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 05b6 4000 ff11 f30c c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0060 2bcf 5800 0054
    0x0020:  0000 0000 d073 d500 a7ff 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  a4ef 0000 c8e9 9411 0000 0000 6b69 7463
    0x0050:  6865 6e20 7369 6e6b 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0200 0000
    0x0070:  0000 0000
20:09:41.696803 IP (tos 0x0, ttl 255, id 1599, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 063f 4000 ff11 f27f c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0060 9017 5800 0054
    0x0020:  0000 0000 d073 d500 b3d8 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  4efa 0000 5952 9411 0000 0000 6b69 7463
    0x0050:  6865 6e20 6672 6964 6765 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0200 0000
    0x0070:  0000 0000
20:09:41.702728 IP (tos 0x0, ttl 255, id 1463, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.102.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 05b7 4000 ff11 f30b c0a8 0066
    0x0010:  c0a8 00ff dd7c dd7c 0060 2245 5800 0054
    0x0020:  0000 0000 d073 d500 91fd 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  fcff 0000 7d4e a00f 0000 0000 6365 696c
    0x0050:  696e 6700 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0400 0000
    0x0070:  0000 0000
20:09:41.720772 IP (tos 0x0, ttl 255, id 1600, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 0640 4000 ff11 f27e c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0060 cde1 5800 0054
    0x0020:  0000 0000 d073 d500 ad96 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  4404 0000 e404 480d 0000 0000 6d69 7272
    0x0050:  6f72 3100 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0400 0000
    0x0070:  0000 0000
20:09:41.746825 IP (tos 0x0, ttl 255, id 1601, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 0641 4000 ff11 f27d c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0060 7d46 5800 0054
    0x0020:  0000 0000 d073 d500 8f3a 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  c6b1 0000 714f 8813 0000 0000 6265 6472
    0x0050:  6f6f 6d00 0000 0000 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0000 0000
    0x0070:  0000 0000
20:09:41.767765 IP (tos 0x0, ttl 255, id 1602, offset 0, flags [DF], proto UDP (17), length 116)
    192.168.0.106.56700 > 192.168.0.255.56700: UDP, length 88
    0x0000:  4500 0074 0642 4000 ff11 f27c c0a8 006a
    0x0010:  c0a8 00ff dd7c dd7c 0060 2bcb 5800 0054
    0x0020:  0000 0000 d073 d500 a7ff 0000 4c49 4658
    0x0030:  5632 0000 0000 0000 0000 0000 6b00 0000
    0x0040:  a4ef 0000 c8e9 9411 0000 0000 6b69 7463
    0x0050:  6865 6e20 7369 6e6b 0000 0000 0000 0000
    0x0060:  0000 0000 0000 0000 0000 0000 0200 0000
    0x0070:  0000 0000
^C
43 packets captured
43 packets received by filter
0 packets dropped by kernel

**Comment by jheld** [comment]
I've made a new post/comment to the multiple bulb issue. That's where this belongs, I think. Either way, there's the tcpdump, hah.

**Comment by jheld** [comment]
I've made a new post/comment to the multiple bulb issue. That's where this belongs, I think. Either way, there's the tcpdump, hah.

**Comment by GNious** [comment]
@jheld ...
First 2 packets looks to be Discovery packets from 192.168.0.109 (android device?)
Next 4 looks like responses from gateways 192.168.0.106 and 192.168.0.102
After that, a bunch of information packets from both gateways about various bulbs.

My thinking here is that your LIFX network got segmented for whichever reason (race-condition if all bulbs turn on at the same time?), and the Python lib doesn't support multiple gateways :( 
There are a couple of ways I think of to support multiple gateways, and since the changes I made just use sendto(data, destination), it shouldn't require tooo much code-change.
If you have an idea for how to force the issue, that Could help with testing any code-changes; I simply don't have enough bulbs here to sanely trigger this particular headache.

Beside that, I think I now have enough information to formulate some sane questions to the LIFX team, which I'll email to them later this week.
- Network behaviour related to segmentation (re-integration?)?
- Mesh between multiple gateways?
- Race-conditions during boot-up, for selecting gateway?
- Triggering segmentation?
